#*****************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# YCC59_3238CQ1.tcl: Tcl script for re-creating project 'YCC59_3238CQ1'
#
# Generated by Vivado on Sat Mar 14 16:21:57 +0300 2026
# IP Build 6138677 on Thu May 22 03:10:11 MDT 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (YCC59_3238CQ1.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/Projects/YCC59_3238CQ1/vivado_project/YCC59_3238CQ1.srcs/sources_1/imports/hdl/design_1_wrapper.v"
#    "D:/Projects/YCC59_3238CQ1/vivado_project/YCC59_3238CQ1.srcs/constrs_1/imports/constr/ebaz4205.xdc"
#    "D:/Projects/YCC59_3238CQ1/vivado_project/YCC59_3238CQ1.srcs/utils_1/imports/synth_1/SPI_master.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/memories/BRAM.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/memories/BRAM_memory_intr.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/DDR/DDRx_intr.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/FIXEDIO/FIXEDIO_intr.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/RS_latch.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/SPI/SPI_intr.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/SPI/SPI_master.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_fsm.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_selftest_fsm.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_boot_prog_fsm.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_main_fsm.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/YCC59_328CQ1_programm.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/address_counter.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/bd_wrapper.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/clk_gen.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/comporator.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/counter.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/data_spi.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/data_to_spi_former.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/delay.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/edge_sense.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/func_spi.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/general_mux.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/parallel_to_serial.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/pulse_generation.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/hdl/common/serial_to_parallel.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/spi_from_data_former.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_top.sv"
#    "D:/Projects/YCC59_3238CQ1/src/design/YCC59_328CQ1_prog/BRAM_mem_init.mem"
#    "D:/Projects/YCC59_3238CQ1/src/tb/YCC59_328CQ1_programm_tb.sv"
#    "D:/Projects/hdl/SPI/SPI_master_tb.sv"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/vivado_project/YCC59_3238CQ1.srcs/sources_1/imports/hdl/design_1_wrapper.v"]"\
 "[file normalize "$origin_dir/vivado_project/YCC59_3238CQ1.srcs/constrs_1/imports/constr/ebaz4205.xdc"]"\
 "[file normalize "$origin_dir/vivado_project/YCC59_3238CQ1.srcs/utils_1/imports/synth_1/SPI_master.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/src/design/hdl/memories/BRAM.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/memories/BRAM_memory_intr.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/DDR/DDRx_intr.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/FIXEDIO/FIXEDIO_intr.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/RS_latch.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/SPI/SPI_intr.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/SPI/SPI_master.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_fsm.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_selftest_fsm.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_boot_prog_fsm.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_main_fsm.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/YCC59_328CQ1_programm.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/address_counter.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/bd_wrapper.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/clk_gen.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/comporator.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/counter.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/data_spi.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/data_to_spi_former.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/delay.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/edge_sense.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/func_spi.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/general_mux.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/parallel_to_serial.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/pulse_generation.sv"]"\
 "[file normalize "$origin_dir/src/design/hdl/common/serial_to_parallel.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/spi_from_data_former.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_top.sv"]"\
 "[file normalize "$origin_dir/src/design/YCC59_328CQ1_prog/BRAM_mem_init.mem"]"\
 "[file normalize "$origin_dir/src/tb/YCC59_328CQ1_programm_tb.sv"]"\
 "[file normalize "$origin_dir/../hdl/SPI/SPI_master_tb.sv"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "YCC59_3238CQ1"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "YCC59_3238CQ1.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/vivado_project"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z010clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z010clg400-1" -objects $obj
set_property -name "platform.board_id" -value "ebaz4205" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "2" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "2" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "201" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/design/hdl/memories/BRAM.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/memories/BRAM_memory_intr.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/DDR/DDRx_intr.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/FIXEDIO/FIXEDIO_intr.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/RS_latch.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/SPI/SPI_intr.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/SPI/SPI_master.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_fsm.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_selftest_fsm.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_boot_prog_fsm.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_main_fsm.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/YCC59_328CQ1_programm.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/address_counter.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/bd_wrapper.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/clk_gen.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/comporator.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/counter.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/data_spi.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/data_to_spi_former.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/delay.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/edge_sense.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/func_spi.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/general_mux.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/parallel_to_serial.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/pulse_generation.sv"] \
 [file normalize "${origin_dir}/src/design/hdl/common/serial_to_parallel.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/spi_from_data_former.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_top.sv"] \
 [file normalize "${origin_dir}/src/design/YCC59_328CQ1_prog/BRAM_mem_init.mem"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/YCC59_3238CQ1.srcs/sources_1/imports/hdl/design_1_wrapper.v"]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sources_1 $f]
}

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/design/hdl/memories/BRAM.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/memories/BRAM_memory_intr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/DDR/DDRx_intr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/FIXEDIO/FIXEDIO_intr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/RS_latch.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/SPI/SPI_intr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/SPI/SPI_master.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_fsm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_3238CQ1_selftest_fsm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_boot_prog_fsm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/FSM/YCC59_328CQ1_main_fsm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/YCC59_328CQ1_programm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/address_counter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/bd_wrapper.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/clk_gen.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/comporator.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/counter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/data_spi.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/data_to_spi_former.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/delay.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/edge_sense.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/func_spi.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/general_mux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/parallel_to_serial.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/pulse_generation.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/hdl/common/serial_to_parallel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/spi_from_data_former.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_top.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/design/YCC59_328CQ1_prog/BRAM_mem_init.mem"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Memory File" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "YCC59_328CQ1_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize ${origin_dir}/vivado_project/YCC59_3238CQ1.srcs/constrs_1/imports/constr/ebaz4205.xdc]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "constr/ebaz4205.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7z010clg400-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/src/tb/YCC59_328CQ1_programm_tb.sv"] \
 [file normalize "${origin_dir}/../hdl/SPI/SPI_master_tb.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/src/tb/YCC59_328CQ1_programm_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/../hdl/SPI/SPI_master_tb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "YCC59_328CQ1_programm_tb" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/vivado_project/YCC59_3238CQ1.srcs/utils_1/imports/synth_1/SPI_master.dcp" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset utils_1 $f]
}

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/SPI_master.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:processing_system7:5.5\
  xilinx.com:ip:axi_bram_ctrl:4.1\
  xilinx.com:ip:smartconnect:1.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:system_ila:1.1\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set DDR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR ]

  set FIXED_IO [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO ]

  set BRAM_PORTA [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:bram_rtl:1.0 BRAM_PORTA ]
  set_property -dict [ list \
   CONFIG.MASTER_TYPE {BRAM_CTRL} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   ] $BRAM_PORTA


  # Create ports
  set o_clk [ create_bd_port -dir O -type clk o_clk ]
  set i_TR1 [ create_bd_port -dir I -from 0 -to 0 i_TR1 ]
  set i_TR2 [ create_bd_port -dir I -from 0 -to 0 i_TR2 ]
  set i_EN [ create_bd_port -dir I -from 0 -to 0 i_EN ]
  set i_DEN [ create_bd_port -dir I -from 0 -to 0 i_DEN ]
  set i_CLK [ create_bd_port -dir I -from 0 -to 0 i_CLK ]
  set i_DIN [ create_bd_port -dir I -from 0 -to 0 i_DIN ]
  set i_OE [ create_bd_port -dir I -from 0 -to 0 i_OE ]
  set i_DOUT [ create_bd_port -dir I -from 0 -to 0 i_DOUT ]
  set i_FEN [ create_bd_port -dir I -from 0 -to 0 i_FEN ]
  set i_FIN [ create_bd_port -dir I -from 0 -to 0 i_FIN ]
  set i_main_fsm_state [ create_bd_port -dir I -from 4 -to 0 i_main_fsm_state ]
  set i_boot_prog_fsm_state [ create_bd_port -dir I -from 2 -to 0 i_boot_prog_fsm_state ]
  set i_selftest_fsm_state [ create_bd_port -dir I -from 2 -to 0 i_selftest_fsm_state ]
  set i_addrb [ create_bd_port -dir I -from 7 -to 0 i_addrb ]
  set i_dout_bram [ create_bd_port -dir I -from 7 -to 0 i_dout_bram ]
  set i_web [ create_bd_port -dir I -from 0 -to 0 i_web ]
  set i_dinb [ create_bd_port -dir I -from 7 -to 0 i_dinb ]

  # Create instance: processing_system7_0, and set properties
  set processing_system7_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0 ]
  set_property -dict [list \
    CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {666.666687} \
    CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.158730} \
    CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {120.000000} \
    CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_CLK0_FREQ {120000000} \
    CONFIG.PCW_CLK1_FREQ {10000000} \
    CONFIG.PCW_CLK2_FREQ {10000000} \
    CONFIG.PCW_CLK3_FREQ {10000000} \
    CONFIG.PCW_DDR_RAM_HIGHADDR {0x0FFFFFFF} \
    CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_EN_EMIO_ENET0 {0} \
    CONFIG.PCW_EN_EMIO_UART0 {0} \
    CONFIG.PCW_EN_ENET0 {0} \
    CONFIG.PCW_EN_SDIO0 {1} \
    CONFIG.PCW_EN_SMC {1} \
    CONFIG.PCW_EN_UART0 {0} \
    CONFIG.PCW_EN_UART1 {1} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {120} \
    CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
    CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_0_PULLUP {enabled} \
    CONFIG.PCW_MIO_0_SLEW {slow} \
    CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_10_PULLUP {enabled} \
    CONFIG.PCW_MIO_10_SLEW {slow} \
    CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_11_PULLUP {enabled} \
    CONFIG.PCW_MIO_11_SLEW {slow} \
    CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_12_PULLUP {enabled} \
    CONFIG.PCW_MIO_12_SLEW {slow} \
    CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_13_PULLUP {enabled} \
    CONFIG.PCW_MIO_13_SLEW {slow} \
    CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_14_PULLUP {enabled} \
    CONFIG.PCW_MIO_14_SLEW {slow} \
    CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_24_PULLUP {enabled} \
    CONFIG.PCW_MIO_24_SLEW {slow} \
    CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_25_PULLUP {enabled} \
    CONFIG.PCW_MIO_25_SLEW {slow} \
    CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_2_SLEW {slow} \
    CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_3_SLEW {slow} \
    CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_40_PULLUP {enabled} \
    CONFIG.PCW_MIO_40_SLEW {slow} \
    CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_41_PULLUP {enabled} \
    CONFIG.PCW_MIO_41_SLEW {slow} \
    CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_42_PULLUP {enabled} \
    CONFIG.PCW_MIO_42_SLEW {slow} \
    CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_43_PULLUP {enabled} \
    CONFIG.PCW_MIO_43_SLEW {slow} \
    CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_44_PULLUP {enabled} \
    CONFIG.PCW_MIO_44_SLEW {slow} \
    CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_45_PULLUP {enabled} \
    CONFIG.PCW_MIO_45_SLEW {slow} \
    CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_4_SLEW {slow} \
    CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_5_SLEW {slow} \
    CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_6_SLEW {slow} \
    CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_7_SLEW {slow} \
    CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_8_SLEW {slow} \
    CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_9_PULLUP {enabled} \
    CONFIG.PCW_MIO_9_SLEW {slow} \
    CONFIG.PCW_MIO_TREE_PERIPHERALS {NAND Flash#unassigned#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#NAND Flash#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#UART\
1#UART 1#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned}\
\
    CONFIG.PCW_MIO_TREE_SIGNALS {cs#unassigned#ale#we_b#data[2]#data[0]#data[1]#cle#re_b#data[4]#data[5]#data[6]#data[7]#data[3]#busy#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#tx#rx#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#clk#cmd#data[0]#data[1]#data[2]#data[3]#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned}\
\
    CONFIG.PCW_NAND_GRP_D8_ENABLE {0} \
    CONFIG.PCW_NAND_NAND_IO {MIO 0 2.. 14} \
    CONFIG.PCW_NAND_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_SD0_GRP_CD_ENABLE {0} \
    CONFIG.PCW_SD0_GRP_POW_ENABLE {0} \
    CONFIG.PCW_SD0_GRP_WP_ENABLE {0} \
    CONFIG.PCW_SD0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45} \
    CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {100} \
    CONFIG.PCW_SDIO_PERIPHERAL_VALID {1} \
    CONFIG.PCW_SMC_PERIPHERAL_FREQMHZ {100} \
    CONFIG.PCW_SMC_PERIPHERAL_VALID {1} \
    CONFIG.PCW_UART0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} \
    CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_UART1_UART1_IO {MIO 24 .. 25} \
    CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {100} \
    CONFIG.PCW_UART_PERIPHERAL_VALID {1} \
    CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {533.333374} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.106} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.106} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.106} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.106} \
    CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {16 Bit} \
    CONFIG.PCW_UIPARAM_DDR_ECC {Disabled} \
    CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K128M16 JT-125} \
    CONFIG.PCW_USE_S_AXI_GP0 {0} \
  ] $processing_system7_0


  # Create instance: axi_bram_ctrl_0, and set properties
  set axi_bram_ctrl_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_bram_ctrl:4.1 axi_bram_ctrl_0 ]
  set_property CONFIG.SINGLE_PORT_BRAM {1} $axi_bram_ctrl_0


  # Create instance: smartconnect_0, and set properties
  set smartconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 smartconnect_0 ]
  set_property CONFIG.NUM_SI {1} $smartconnect_0


  # Create instance: proc_sys_reset_0, and set properties
  set proc_sys_reset_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_0 ]

  # Create instance: system_ila_0, and set properties
  set system_ila_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:system_ila:1.1 system_ila_0 ]
  set_property -dict [list \
    CONFIG.C_ADV_TRIGGER {true} \
    CONFIG.C_DATA_DEPTH {4096} \
    CONFIG.C_EN_STRG_QUAL {1} \
    CONFIG.C_MON_TYPE {NATIVE} \
    CONFIG.C_NUM_OF_PROBES {17} \
    CONFIG.C_PROBE10_WIDTH {5} \
    CONFIG.C_PROBE11_WIDTH {3} \
    CONFIG.C_PROBE12_WIDTH {3} \
    CONFIG.C_PROBE13_WIDTH {8} \
    CONFIG.C_PROBE14_WIDTH {8} \
    CONFIG.C_PROBE15_WIDTH {1} \
    CONFIG.C_PROBE16_WIDTH {8} \
    CONFIG.C_PROBE7_WIDTH {1} \
    CONFIG.C_PROBE8_WIDTH {1} \
    CONFIG.C_PROBE9_WIDTH {1} \
    CONFIG.C_PROBE_WIDTH_PROPAGATION {MANUAL} \
  ] $system_ila_0


  # Create interface connections
  connect_bd_intf_net -intf_net axi_bram_ctrl_0_BRAM_PORTA [get_bd_intf_pins axi_bram_ctrl_0/BRAM_PORTA] [get_bd_intf_ports BRAM_PORTA]
  connect_bd_intf_net -intf_net processing_system7_0_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins processing_system7_0/DDR]
  connect_bd_intf_net -intf_net processing_system7_0_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins processing_system7_0/FIXED_IO]
  connect_bd_intf_net -intf_net processing_system7_0_M_AXI_GP0 [get_bd_intf_pins smartconnect_0/S00_AXI] [get_bd_intf_pins processing_system7_0/M_AXI_GP0]
  connect_bd_intf_net -intf_net smartconnect_0_M00_AXI [get_bd_intf_pins axi_bram_ctrl_0/S_AXI] [get_bd_intf_pins smartconnect_0/M00_AXI]

  # Create port connections
  connect_bd_net -net Net  [get_bd_pins proc_sys_reset_0/peripheral_aresetn] \
  [get_bd_pins smartconnect_0/aresetn] \
  [get_bd_pins axi_bram_ctrl_0/s_axi_aresetn]
  connect_bd_net -net i_CLK_1  [get_bd_ports i_CLK] \
  [get_bd_pins system_ila_0/probe4]
  connect_bd_net -net i_DEN_1  [get_bd_ports i_DEN] \
  [get_bd_pins system_ila_0/probe3]
  connect_bd_net -net i_DIN_1  [get_bd_ports i_DIN] \
  [get_bd_pins system_ila_0/probe5]
  connect_bd_net -net i_DOUT_1  [get_bd_ports i_DOUT] \
  [get_bd_pins system_ila_0/probe7]
  connect_bd_net -net i_EN_1  [get_bd_ports i_EN] \
  [get_bd_pins system_ila_0/probe2]
  connect_bd_net -net i_FEN_1  [get_bd_ports i_FEN] \
  [get_bd_pins system_ila_0/probe8]
  connect_bd_net -net i_FIN_1  [get_bd_ports i_FIN] \
  [get_bd_pins system_ila_0/probe9]
  connect_bd_net -net i_OE_1  [get_bd_ports i_OE] \
  [get_bd_pins system_ila_0/probe6]
  connect_bd_net -net i_TR1_1  [get_bd_ports i_TR1] \
  [get_bd_pins system_ila_0/probe0]
  connect_bd_net -net i_TR2_1  [get_bd_ports i_TR2] \
  [get_bd_pins system_ila_0/probe1]
  connect_bd_net -net i_addrb_1  [get_bd_ports i_addrb] \
  [get_bd_pins system_ila_0/probe13]
  connect_bd_net -net i_boot_prog_fsm_state_1  [get_bd_ports i_boot_prog_fsm_state] \
  [get_bd_pins system_ila_0/probe11]
  connect_bd_net -net i_dinb_1  [get_bd_ports i_dinb] \
  [get_bd_pins system_ila_0/probe16]
  connect_bd_net -net i_dout_bram_1  [get_bd_ports i_dout_bram] \
  [get_bd_pins system_ila_0/probe14]
  connect_bd_net -net i_main_fsm_state_1  [get_bd_ports i_main_fsm_state] \
  [get_bd_pins system_ila_0/probe10]
  connect_bd_net -net i_selftest_fsm_state_1  [get_bd_ports i_selftest_fsm_state] \
  [get_bd_pins system_ila_0/probe12]
  connect_bd_net -net i_web_1  [get_bd_ports i_web] \
  [get_bd_pins system_ila_0/probe15]
  connect_bd_net -net processing_system7_0_FCLK_CLK0  [get_bd_pins processing_system7_0/FCLK_CLK0] \
  [get_bd_pins processing_system7_0/M_AXI_GP0_ACLK] \
  [get_bd_pins axi_bram_ctrl_0/s_axi_aclk] \
  [get_bd_pins smartconnect_0/aclk] \
  [get_bd_pins proc_sys_reset_0/slowest_sync_clk] \
  [get_bd_pins system_ila_0/clk] \
  [get_bd_ports o_clk]
  connect_bd_net -net processing_system7_0_FCLK_RESET0_N  [get_bd_pins processing_system7_0/FCLK_RESET0_N] \
  [get_bd_pins proc_sys_reset_0/ext_reset_in]

  # Create address segments
  assign_bd_address -offset 0x40000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces processing_system7_0/Data] [get_bd_addr_segs axi_bram_ctrl_0/S_AXI/Mem0] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"1.3195",
   "Default View_TopLeft":"-398,-1448",
   "ExpandedHierarchyInLayout":"",
   "PinnedBlocks":"/axi_bram_ctrl_0|/processing_system7_0|/smartconnect_0|/proc_sys_reset_0|/system_ila_0|",
   "PinnedPorts":"DDR|FIXED_IO|o_clk|i_FIN|i_CLK|i_EN|i_FEN|i_DIN|i_OE|i_TR2|i_DEN|i_TR1|i_DOUT|i_main_fsm_state|i_boot_prog_fsm_state|i_selftest_fsm_state|BRAM_PORTA|i_addrb|i_dout_bram|i_dinb|i_web|",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0
#  -string -flagsOSRD
preplace port DDR -pg 1 -lvl 4 -x 1250 -y -180 -defaultsOSRD
preplace port FIXED_IO -pg 1 -lvl 4 -x 1250 -y -150 -defaultsOSRD
preplace port BRAM_PORTA -pg 1 -lvl 4 -x 1250 -y -520 -defaultsOSRD
preplace port port-id_o_clk -pg 1 -lvl 4 -x 1250 -y -40 -defaultsOSRD
preplace portBus i_TR1 -pg 1 -lvl 0 -x -180 -y -1430 -defaultsOSRD
preplace portBus i_TR2 -pg 1 -lvl 0 -x -180 -y -1400 -defaultsOSRD
preplace portBus i_EN -pg 1 -lvl 0 -x -180 -y -1370 -defaultsOSRD
preplace portBus i_DEN -pg 1 -lvl 0 -x -180 -y -1340 -defaultsOSRD
preplace portBus i_CLK -pg 1 -lvl 0 -x -180 -y -1310 -defaultsOSRD
preplace portBus i_DIN -pg 1 -lvl 0 -x -180 -y -1280 -defaultsOSRD
preplace portBus i_OE -pg 1 -lvl 0 -x -180 -y -1250 -defaultsOSRD
preplace portBus i_DOUT -pg 1 -lvl 0 -x -180 -y -1220 -defaultsOSRD
preplace portBus i_FEN -pg 1 -lvl 0 -x -180 -y -1190 -defaultsOSRD
preplace portBus i_FIN -pg 1 -lvl 0 -x -180 -y -1160 -defaultsOSRD
preplace portBus i_main_fsm_state -pg 1 -lvl 0 -x -180 -y -1130 -defaultsOSRD
preplace portBus i_boot_prog_fsm_state -pg 1 -lvl 0 -x -180 -y -1100 -defaultsOSRD
preplace portBus i_selftest_fsm_state -pg 1 -lvl 0 -x -180 -y -1070 -defaultsOSRD
preplace portBus i_addrb -pg 1 -lvl 0 -x -180 -y -1040 -defaultsOSRD
preplace portBus i_dout_bram -pg 1 -lvl 0 -x -180 -y -1010 -defaultsOSRD
preplace portBus i_web -pg 1 -lvl 0 -x -180 -y -980 -defaultsOSRD
preplace portBus i_dinb -pg 1 -lvl 0 -x -180 -y -950 -defaultsOSRD
preplace inst processing_system7_0 -pg 1 -lvl 1 -x 310 -y -140 -defaultsOSRD
preplace inst axi_bram_ctrl_0 -pg 1 -lvl 3 -x 1080 -y -520 -defaultsOSRD
preplace inst smartconnect_0 -pg 1 -lvl 2 -x 780 -y -450 -defaultsOSRD
preplace inst proc_sys_reset_0 -pg 1 -lvl 1 -x 310 -y -360 -defaultsOSRD
preplace inst system_ila_0 -pg 1 -lvl 2 -x 780 -y -1210 -defaultsOSRD
preplace netloc Net 1 1 2 640 -530 910
preplace netloc i_CLK_1 1 0 2 NJ -1310 510
preplace netloc i_DEN_1 1 0 2 NJ -1340 520
preplace netloc i_DIN_1 1 0 2 NJ -1280 500
preplace netloc i_DOUT_1 1 0 2 NJ -1220 N
preplace netloc i_EN_1 1 0 2 NJ -1370 620
preplace netloc i_FEN_1 1 0 2 NJ -1190 500
preplace netloc i_FIN_1 1 0 2 NJ -1160 500
preplace netloc i_OE_1 1 0 2 NJ -1250 500
preplace netloc i_TR1_1 1 0 2 NJ -1430 640
preplace netloc i_TR2_1 1 0 2 NJ -1400 630
preplace netloc i_boot_prog_fsm_state_1 1 0 2 NJ -1100 520
preplace netloc i_main_fsm_state_1 1 0 2 NJ -1130 510
preplace netloc i_selftest_fsm_state_1 1 0 2 NJ -1070 530
preplace netloc processing_system7_0_FCLK_CLK0 1 0 4 110 -250 610 -540 940 -190 1220
preplace netloc processing_system7_0_FCLK_RESET0_N 1 0 2 120 -240 500
preplace netloc i_addrb_1 1 0 2 NJ -1040 620
preplace netloc i_dout_bram_1 1 0 2 NJ -1010 630
preplace netloc i_web_1 1 0 2 NJ -980 640
preplace netloc i_dinb_1 1 0 2 NJ -950 650
preplace netloc processing_system7_0_DDR 1 1 3 N -180 N -180 N
preplace netloc processing_system7_0_FIXED_IO 1 1 3 N -160 N -160 1210
preplace netloc processing_system7_0_M_AXI_GP0 1 1 1 650 -470n
preplace netloc smartconnect_0_M00_AXI 1 2 1 950 -540n
preplace netloc axi_bram_ctrl_0_BRAM_PORTA 1 3 1 N -520
levelinfo -pg 1 -180 310 780 1080 1250
pagesize -pg 1 -db -bbox -sgen -420 -1460 1680 200
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_1()

cr_bd_design_1 ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z010clg400-1 -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7z010clg400-1" -objects $obj
set_property -name "incremental_checkpoint" -value "$proj_dir/${_xil_proj_name_}.srcs/utils_1/imports/synth_1/SPI_master.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z010clg400-1 -flow {Vivado Implementation 2025} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7z010clg400-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
